version: 0.2
phases:
  install:
    commands:
      - "touch .npmignore"
      - "npm install -g gatsby"
      - "npm install -g yarn"
  pre_build:
    commands:
      - "yarn install"
  build:
    commands:
      - "yarn run build"
  post_build:
    commands:
      - aws s3 sync ./public/ s3://cathyiscool.com --delete
cache:
  paths:
    - ".cache/*"
    - "node_modules/*"
    - "public/*"
